import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');

console.log(`
🐺 Welcome to the FangOps Setup Wizard 🐺
-----------------------------------------
This wizard will help you configure your AI Agent Control Plane.
We will generate a .env file for you.
`);

async function main() {
    // Check if .env already exists
    if (fs.existsSync(envPath)) {
        const { overwrite } = await inquirer.prompt([{
            type: 'confirm',
            name: 'overwrite',
            message: 'A .env file already exists. Do you want to overwrite it?',
            default: false
        }]);

        if (!overwrite) {
            console.log('Setup aborted. Your existing .env file was not modified.');
            return;
        }
    }

    const answers = await inquirer.prompt([
        {
            type: 'list',
            name: 'nodeEnv',
            message: 'What environment are you deploying to?',
            choices: ['development', 'production'],
            default: 'development'
        },
        {
            type: 'input',
            name: 'openaiKey',
            message: 'Enter your OpenAI API Key (sk-...):',
            validate: input => input.startsWith('sk-') ? true : 'Key should start with sk-'
        },
        {
            type: 'input',
            name: 'slackWebhook',
            message: 'Enter your Slack Webhook URL (optional, press Enter to skip):',
            default: ''
        },
        {
            type: 'input',
            name: 'jwtSecret',
            message: 'Enter a JWT Secret string for authentication:',
            default: () => require('crypto').randomBytes(32).toString('hex')
        }
    ]);

    const envContent = `
# ==========================================
# FangOps Environment Configuration
# Auto-generated by setup wizard
# ==========================================

NODE_ENV=${answers.nodeEnv}

# ---- API Server ----
API_HOST=0.0.0.0
API_PORT=3000

# ---- Dashboard ----
DASHBOARD_PORT=5173

# ---- Database ----
# Defaulting to local SQLite for easy setup
DATABASE_URL=file:./local.db

# ---- Security ----
JWT_SECRET=${answers.jwtSecret}

# ---- LLM Configuration Defaults ----
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4o

# ---- Provider API Keys ----
OPENAI_API_KEY=${answers.openaiKey}
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=

# ---- Notifications (Reporter Hand) ----
SLACK_WEBHOOK_URL=${answers.slackWebhook}
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
    `.trim();

    fs.writeFileSync(envPath, envContent + '\n', 'utf8');

    console.log(`
✅ Setup Complete! Your .env file has been generated.

Next steps:
1. Run 'pnpm run db:push' (if configured in your package.json) or run seed script to initialize the SQLite database.
2. Run 'pnpm run dev' to start the Monorepo.
3. Open http://localhost:5173 in your browser.
    `);
}

main().catch(err => {
    console.error('Setup failed:', err);
});
